# Generated by Django 5.1.3 on 2024-11-20 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('teacher', '0003_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
