# Generated by Django 5.1.3 on 2024-11-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('teacher', '0004_alter_teacher_class_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
