# Generated by Django 5.1.3 on 2024-11-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='TEACHER',
        ),
    ]
