# Generated by Django 5.1.3 on 2024-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('total_student', models.CharField(blank=True, max_length=5, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
