# Generated by Django 5.1.3 on 2024-11-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marks',
            table='MARKS',
        ),
    ]
